
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.graficas.codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nombre = 24;
  public static final int Coma = 26;
  public static final int Llaves_c = 35;
  public static final int Llaves_a = 34;
  public static final int PIE = 5;
  public static final int Titulo = 7;
  public static final int Corchete_c = 19;
  public static final int ejeY = 9;
  public static final int ejeX = 8;
  public static final int Cantidad = 36;
  public static final int Corchete_a = 18;
  public static final int BARRAS = 4;
  public static final int Total = 12;
  public static final int Vacio = 22;
  public static final int Etiqueta = 10;
  public static final int Division = 30;
  public static final int Ejecutar = 38;
  public static final int Parentesis_c = 33;
  public static final int Dos_p = 20;
  public static final int Parentesis_a = 32;
  public static final int EOF = 0;
  public static final int P_coma = 16;
  public static final int error = 1;
  public static final int Tipo = 15;
  public static final int ERROR = 23;
  public static final int Unir = 14;
  public static final int Extra = 11;
  public static final int Identificador = 6;
  public static final int Espacio = 21;
  public static final int Resta = 29;
  public static final int Porcentaje = 37;
  public static final int DEF = 2;
  public static final int DEFINIR = 3;
  public static final int Multiplicacion = 31;
  public static final int Decimal = 25;
  public static final int Valores = 13;
  public static final int Numero = 27;
  public static final int Suma = 28;
  public static final int Igual = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "DEFINIR",
  "BARRAS",
  "PIE",
  "Identificador",
  "Titulo",
  "ejeX",
  "ejeY",
  "Etiqueta",
  "Extra",
  "Total",
  "Valores",
  "Unir",
  "Tipo",
  "P_coma",
  "Igual",
  "Corchete_a",
  "Corchete_c",
  "Dos_p",
  "Espacio",
  "Vacio",
  "ERROR",
  "Nombre",
  "Decimal",
  "Coma",
  "Numero",
  "Suma",
  "Resta",
  "Division",
  "Multiplicacion",
  "Parentesis_a",
  "Parentesis_c",
  "Llaves_a",
  "Llaves_c",
  "Cantidad",
  "Porcentaje",
  "Ejecutar"
  };
}

